### ISSUE TITLE
Doesn’t work properly with Eclipse X

### ISSUE THREAD

**Issue by sohsatoh** [Ominousness/MitsuhaXI#11]
I cannot see wave effect (white version) in case of I installed Eclipse X.
I know the white colour reverted by Eclipse, and it is the feature of the tweak. Is it possible to work with EclipseX?
(sorry, i’m not good at english.)

**Comment by Ominousness** [comment]
Does it work with the red version?

**Comment by jatin2910** [comment]
nope doesn't with red either

**Comment by Ominousness** [comment]
I'll wait for the stable release of EclipseX then.

**Comment by crackeyes** [comment]
the red and white do work with eclipse. The white is just to dark to see  well. The red works fine for me
