### ISSUE TITLE
Artwort is too high in Spotify.

### ISSUE THREAD

**Issue by Insaneous** [Ominousness/MitsuhaXI#16]
In the new version album artwork goes on the name of a playlist.
![Image](https://i.imgur.com/zEnre6i.jpg)

**Comment by Ominousness** [comment]
Fixed in [0.2.0](https://github.com/Ominousness/MitsuhaXI/releases/tag/v0.2.0).

**Comment by Insaneous** [comment]
![Still same🤔](https://i.imgur.com/TrdDbz2.jpg)

**Comment by Insaneous** [comment]
Still same🤔
