### ISSUE TITLE
Artwork is still high for me

### ISSUE THREAD

**Issue by xMickey** [Ominousness/MitsuhaXI#19]
in the changes, it says that the artwork being too high issue was fixed. Not for me.
![image](https://user-images.githubusercontent.com/23196378/35480667-a3ea24b0-0413-11e8-9f93-2aaf5aa6f12a.jpg)

**Comment by Ominousness** [comment]
Are you using any other tweaks?

**Comment by xMickey** [comment]
well apart from colorflow nothing that could impact Spotify

**Comment by avoss19** [comment]
I am having the same issue on an iPhone 7 on 11.1.2

**Comment by Ominousness** [comment]
@xMickey @avoss19 will be fixed in 0.4.1. Meanwhile check out the new update: https://www.reddit.com/r/jailbreak/comments/8hqfb6/update_mitsuhaxi_040_beta_notification_audio/
