### ISSUE TITLE
When using Fluidity, Wave is misaligned.

### ISSUE THREAD

**Issue by KikeMartinG** [Ominousness/MitsuhaXI#2]
Since the status bar gets bigger, the wave gets pulled down, and so it gets misaligned.
Here’s the screenshot so u know what i mean.

http://i67.tinypic.com/negtjq.jpg

![b558ef30-3409-48c9-bdf7-b331839262d6](https://user-images.githubusercontent.com/15319495/35186478-3f9a6ab6-fdd2-11e7-96ed-3c3afd72da24.jpeg)

**Comment by Ominousness** [comment]
This will be resolved when I'll get preferences working or find another way to position the visualizer layer.

**Comment by Ominousness** [comment]
Fixed in [0.2.0](https://github.com/Ominousness/MitsuhaXI/releases/tag/v0.2.0).
