### ISSUE TITLE
Any support for Cydia?

### ISSUE THREAD

**Issue by KieranTH** [Ominousness/MitsuhaXI#22]
Do you have an addable Repo for Cydia, seeing the current Mitsuha doesn't support IOS 11 on Cydia

Any help is appreciated.

**Comment by Favna** [comment]
You can install the deb from releases manually. Transfer the deb to your phone to any folder using SFTP (FileZilla / WinsCP) then go into a terminal SSH session and  type `dpkg -i whatever.you.named.the.file.deb`

**Comment by Ominousness** [comment]
Sorry guys, I was kinda busy with work, I'll try to publish it next week.

**Comment by Favna** [comment]
All good! work has priority any day!

**Comment by Ominousness** [comment]
https://www.reddit.com/r/jailbreak/comments/8hqfb6/update_mitsuhaxi_040_beta_notification_audio/

@KieranTH @Favna A little delay, but it's there :D
