### ISSUE TITLE
Spotify album art is too close to wave with -11 when before 0.4.1 this didn't happen 

### ISSUE THREAD

**Issue by jsex** [Ominousness/MitsuhaXI#25]

**Comment by Ominousness** [comment]
Just increase the wave offset in settings.

**Comment by jsex** [comment]
The main issue is that 0.4.1 made the album art way to close to the waves that are negative, the positive side of the wave is too low for me. I put specifically -11 so you know what to test in the negative section but I guess if you don’t feel like actually fixing the issue for whatever reason then thank goodness there’s Always the older versions that actually work.

**Comment by jsex** [comment]
If it didn’t happen in 0.4.0 with the same settings I had with 2.0 is because 0.4.1 BROKE something or something happened in the code that made it have that effect

**Comment by Ominousness** [comment]
Could I see a screenshot?

**Comment by jsex** [comment]
![658349de-5f10-47f2-8242-e89aebd7835e](https://user-images.githubusercontent.com/38796140/39922985-c7a27272-54ef-11e8-8933-e0034e450380.png)
![a5dc3fcc-f36e-4c21-b652-16b263507294](https://user-images.githubusercontent.com/38796140/39922986-c7b72cc6-54ef-11e8-8f5d-0a01583486fe.png)

Pretty sure the first screenshot is 0.2.0 since I can’t get 0.4.0 from repo but the second one should be 0.4.1 bothbarebon thebsame settings, by the way sorry if I sounded rude that wasn’t my intention

**Comment by Ominousness** [comment]
I'll just bring back that feature everybody complained about as an option. Should make everyone happy.

**Comment by Ominousness** [comment]
Wait for 0.4.2.

**Comment by Ominousness** [comment]
@jsex https://www.reddit.com/r/jailbreak/comments/8ipro0/update_mitsuhaxi_042_beta_artsy_support_spotify/

**Comment by jsxn** [comment]
Yeah it’s an amazing update for me, color matching works better. Though I have to use artsy over ccmusicartwork because the cc wave doesn’t show. Lastly also figured out why for some songs my wave wasn’t moving as much with fft off, the frame per second thing the higher it is can effect how much the wave moves for some songs
