### ISSUE TITLE
Not working on ios 11.4 b3 

### ISSUE THREAD

**Issue by iammssachdeva** [Ominousness/MitsuhaXI#37]
Hi... it's not working.. for some reason.. I have enabled it of course.
Device iPhone 8
Can you please help me?
![img_0011](https://user-images.githubusercontent.com/41124506/42623496-a421cab0-85e0-11e8-95ee-9e9dcab72062.PNG)
![img_0012](https://user-images.githubusercontent.com/41124506/42623498-a45d21be-85e0-11e8-92e8-593ed3b65538.PNG)

**Comment by Ominousness** [comment]
Try running iCleaner, restarting mediaserverd in MitsuhaXI settings and respringing.

**Comment by iammssachdeva** [comment]
@Ominousness 80% tweak is working. 
I have attached the screenshots.... 
You can see on the CC and CC (3D Touch), it's not working properly. It is creating a box shape from below. Other than that it's working perfect. 
![img_0018](https://user-images.githubusercontent.com/41124506/42684481-d7c30fc8-86ad-11e8-8fca-454d6958b059.PNG)
![img_0019](https://user-images.githubusercontent.com/41124506/42684484-d7ff88a4-86ad-11e8-9401-b1c45146092e.PNG)
![img_0020](https://user-images.githubusercontent.com/41124506/42684486-d8357cc0-86ad-11e8-8b9c-d4927a401f2f.PNG)
![img_0021](https://user-images.githubusercontent.com/41124506/42684487-d863fe60-86ad-11e8-885a-d5904595eb3d.PNG)

**Comment by iammssachdeva** [comment]
the problem is solved
