### ISSUE TITLE
No background artwork and no rounded edges on player in CC

### ISSUE THREAD

**Issue by Galbraithm** [Ominousness/MitsuhaXI#38]
I've seen screenshots of plenty of people having the album artwork displayed as a background on the player but it doe not show up for me. The player is just blurred. The bottom of the player also does not have rounded edges (actually just the wave sticking down further than the player).
![img_0224](https://user-images.githubusercontent.com/41162110/42643028-2b447508-85c6-11e8-91c3-4363a6a83e5a.PNG)

**Comment by Ominousness** [comment]
My tweak doesn't do that, it is done by Artsy.

As for the rounded corners, it'll be fixed in the next update.
