### ISSUE TITLE
Offcentered Spotify artwork?

### ISSUE THREAD

**Issue by DylanB00** [Ominousness/MitsuhaXI#4]
First time using this tweak and I love it. However, my artwork seems to be aligned to the right side of my screen when using Spotify on my iPhone X on 11.1.2. Any suggestions?

**Comment by wewladdo** [comment]
That happens only when there are song lyrics included behind the artwork. Also the tweak causes crashes if used with ColorFlow3 sometimes.

**Comment by Ominousness** [comment]
I am aware. I've fixed that but I'm too lazy to compile and package it.

**Comment by DylanB00** [comment]
Let me know when it’s updated

**Comment by Ominousness** [comment]
Try the [latest release](https://github.com/Ominousness/MitsuhaXI/releases/tag/v0.1.1).

**Comment by sohsatoh** [comment]
The latest release seems like broken.
I cannot see the wave effect on Music app, and still offcentered on Spotify. (iPhone X)

**Comment by Ominousness** [comment]
I've noticed it's still off-centered :/

Could you scroll down to "Up Next" and take a screenshot?

**Comment by sohsatoh** [comment]
Sorry, I was wrong.
In case of you installed EclipseX, the wave become black colour. (i could see the wave on the previous release of MitsuhaXI, red)

**Comment by Ominousness** [comment]
@sohsatoh then you'll have to wait for the Preference update.

**Comment by Ominousness** [comment]
@DylanB00 @wewladdo @sohsatoh Should be fixed now.

https://github.com/Ominousness/MitsuhaXI/releases/tag/v0.1.2

**Comment by Ominousness** [comment]
I'll close this now.
