### ISSUE TITLE
Tweak not working on my device. iP6 11.1.2

### ISSUE THREAD

**Issue by mattp12** [Ominousness/MitsuhaXI#5]
The area appears in the music app, but no waves are appearing. 

This happens with the red and white variants.

The issue persists through multiple resprings.

Tweaklist : 

Barmoji
ByeByeHud
DarkMessages
Dim
DockAlpha
Fluidity (currently disabled)
FlatSafariURL
LiveIconDisabler
NoPageDots
PauseOnMute
Twig
Zeppelin

**Comment by Ominousness** [comment]
Could you post a screenshot? Did you try respringing your device?

Also try 'killall -9 Music'

**Comment by kikokoko95** [comment]
In my iPhone 6s it doesn’t work when using headphones, but it works great on speakers

**Comment by kikokoko95** [comment]
But I’m not using wireless earphones, I’m using the EarPods :/ is that normal? I’ve got fluidity and i8corners installed

**Comment by mattp12** [comment]
@Ominousness I tried killing the music app and also respringing (when it was installed).
I would give a screenshot if my Filza app wasn't crashing and if I could reinstall the tweak. However, it is basically the same result as the picture shown here : https://github.com/Ominousness/MitsuhaXI/issues/6

I'm also not using wireless/bluetooth audio outputs.

**Comment by Ominousness** [comment]
@kikokoko95 @mattp12 3.5mm earphones?

Apparently the issue also happens with 3.5mm.

**Comment by mattp12** [comment]
@Ominousness Yup - headphone jack. Weird issue.

**Comment by Ominousness** [comment]
I don't have a device to test on that has a 3.5mm jack, so just subscribe to #3 and when I'll fix Bluetooth audio then I'll post a test build and we'll work this out.
