### ISSUE TITLE
not working on iPhone SE 11.1.2

### ISSUE THREAD

**Issue by IZNEK** [Ominousness/MitsuhaXI#6]
The area appears in the music app, but no waves are appearing.
This happens with the red and white variants.
The issue persists through multiple resprings, reboots, re-jailbreakd.

Tweaklist :

AppColorBadges
BlurryBadges
Cercube For Youtube
Fluidity ( disabled )
Immortal
Noctis XI Lite
RespringProgress
SwipeSelection

Screenshot :

![img_2245](https://user-images.githubusercontent.com/35696513/35229155-f9f74c3c-ff92-11e7-9b17-9414ac08b4a1.PNG)

**Comment by IZNEK** [comment]
No, doesn’t work with iphone speaker, headphones, bluetooth, all

**Comment by Ominousness** [comment]
That's weird, still probably related to #3. I'll let you know when I fix #3.

**Comment by Ominousness** [comment]
Try the [latest release](https://github.com/Ominousness/MitsuhaXI/releases/tag/v0.1.1).

**Comment by IZNEK** [comment]
it's working thanks
Closed
