### ISSUE TITLE
Could you combine Colorflow + MitsuhaXI?

### ISSUE THREAD

**Issue by sohsatoh** [Ominousness/MitsuhaXI#8]
I don't know how it would be difficult, but I think it will be awesome one!
https://www.reddit.com/r/jailbreak/comments/7sado7/request_help_make_this_new_player_come_to_life/

**Comment by Ominousness** [comment]
I will look into this.

**Comment by Ominousness** [comment]
Implemented in 0.4.0 (mediaserverd branch).
